In [94]:
import tensorflow as tf

def docs(func):
    """Fungsi untuk menampilkan dokumentasi"""
    
    
    print(func.__doc__)

## Membuat tensor

### menggunakan python iterable

In [2]:
unchangeable_tensor = tf.constant((8,0,2,7))
unchangeable_tensor

NameError: name 'tf' is not defined

### menggunakan numpy

In [ ]:
# import numpy
import numpy as np

In [ ]:
X = np.arange(0,10,.5)

In [3]:
tensor_X = tf.constant(X)
tensor_X

NameError: name 'tf' is not defined

### menggunakan nilai acak
membuat tensor dengan nilai acak dengan 2 dimensi dan shape 4,4
* Menggunakan normal distribution
* Menggunakan uniform

In [25]:
tf.random.set_seed(42)
acak_normal_Z = tf.random.normal((4,4))
acak_normal_Z

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 ],
       [-2.3880599 , -1.0392479 , -0.5573232 ,  0.539707  ],
       [ 1.6994323 ,  0.28893656, -1.5066116 , -0.26454744],
       [-0.59722406, -1.9171132 , -0.62044144,  0.8504023 ]],
      dtype=float32)>

In [24]:
tf.random.set_seed(42)
acak_uniform_Z = tf.random.uniform((4,4))
acak_uniform_Z

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255],
       [0.03366041, 0.68467236, 0.74011743, 0.8724445 ],
       [0.22632635, 0.22319686, 0.3103881 , 0.7223358 ],
       [0.13318717, 0.5480639 , 0.5746088 , 0.8996835 ]], dtype=float32)>

## Merubah tensor

### merubah nilai tensor

In [19]:
X = tf.Variable([[8,0],[2,7]])
X

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[8, 0],
       [2, 7]], dtype=int32)>

In [42]:
X[0,1].assign(10)
X

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 8, 10],
       [ 2,  7]], dtype=int32)>

Tensor yang dibuat dengan *constant* tidak dapat dirubah nilainya.

In [50]:
X_constant = tf.constant([[8,0],[2,7]])
try:
    X_constant[1,1].assign(20)
except Exception as e:
    print(e)

'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'


Oke, ada solusinya

In [56]:
X_constant = tf.Variable(X_constant)
X_constant[1,1].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[  8,   0],
       [  2, 100]], dtype=int32)>

### merubah tipe data tensor

In [61]:
X_constant.dtype

tf.int32

In [81]:
new_X_constant = tf.cast(X_constant, dtype=tf.float32)
new_X_constant.dtype

tf.float32

### meruba shape dari tensor

In [82]:
new_X_constant.shape

TensorShape([2, 2])

In [83]:
new_X_constant = tf.reshape(new_X_constant,[4,])
new_X_constant.shape

TensorShape([4])

### Menghapus dimensi dengan axis yang kosong

In [133]:
### Menghapus matrix kosong
X = tf.constant([[[[[[[[[1,5,7]]]]]]]]])
X, tf.squeeze(X)

(<tf.Tensor: shape=(1, 1, 1, 1, 1, 1, 1, 1, 3), dtype=int32, numpy=array([[[[[[[[[1, 5, 7]]]]]]]]], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 5, 7], dtype=int32)>)

## Operasi dasar matematika dan perkalian matrix pada terhadap tensor

In [86]:
X = tf.constant([[8,9],[7,2]])
y = tf.constant([[2,1],[3,8]])
X, y

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[8, 9],
        [7, 2]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 1],
        [3, 8]], dtype=int32)>)

### Penambahan
Dapat menggunakan + atau `tf.math.add`

In [89]:
X + y == tf.math.add(X,y)

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

### Pengurangan
dapat menggunakna - atau `tf.math.subtract`

In [97]:
X-y == tf.math.subtract(X,y)

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

### Perkalian dan Pembagina

In [99]:
X * y == tf.math.multiply(X,y), X / y == tf.math.divide(X,y)

(<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True]])>)

### Perkalian Matrix

In [100]:
X ** y == X * y

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[False,  True],
       [False, False]])>

In [106]:
X @ y , X * y

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[43, 80],
        [20, 23]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[16,  9],
        [21, 16]], dtype=int32)>)

In [ ]:
tf.matmul(X,y)

## Agregating tensor

### min, max

In [118]:
tf.reduce_min(X), tf.reduce_max(X),tf.reduce_mean(X),tf.reduce_sum(X)

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>,
 <tf.Tensor: shape=(), dtype=int32, numpy=26>)

### Variance dan standard deviasi

In [127]:
tf.math.reduce_std(tf.cast(X,tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=2.6925824>

In [134]:
tf.math.reduce_variance(tf.cast(X,tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=6.222223>

## Squeezing tensor (Menghapus satu demensi tunggal tensor)

In [135]:
Z = tf.constant([[[[[1,2],[1,2]]]],[[[[1,2],[1,2]]]]])
Z.shape

TensorShape([2, 1, 1, 2, 2])

In [144]:
Y = tf.squeeze(Z)
Y.shape

TensorShape([2, 2, 2])

In [147]:
O = tf.one_hot([1,2,3,4,5,6,0],6)
O

<tf.Tensor: shape=(7, 6), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]], dtype=float32)>

In [154]:
O_car = tf.one_hot([0,1,2,3,4],5, on_value='F', off_value='B')
O_car

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'F', b'B', b'B', b'B', b'B'],
       [b'B', b'F', b'B', b'B', b'B'],
       [b'B', b'B', b'F', b'B', b'B'],
       [b'B', b'B', b'B', b'F', b'B'],
       [b'B', b'B', b'B', b'B', b'F']], dtype=object)>